### ISSUE TITLE
How use this image in .gitlab-ci.yml in docker exector?

### ISSUE THREAD

**Issue by patsevanton** [alpine-docker/helm#60]
Hello! I try use this image in .gitlab-ci.yml in docker exector.
My .gitlab-ci.yml:
```
image: alpine/helm:3.12.3

variables:
  NAMESPACE:
    value: "default"

stages:
  - lint
  - check chart

lint:
  stage: lint
  script:
    - helm lint .
    - helm template .
  tags:
    - docker

dry-run:
  stage: check chart
  script:
    - helm -n "$NAMESPACE" ls
    - >
      helm -n default upgrade -i --dry-run --debug app-chart . 
  tags:
    - docker
```

Can the alpine project create a helm image for run in .gitlab-ci.yml ?
